name: Testing automatic building
run-name: petclinic deployment
on: [push]
jobs:
  Is-This-Arbitrary:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /home/runner/work/petclinic/petclinic
    steps:
      - name: "hallo dit is een naam"
        run: pwd
      - name: git init
        run: git init
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - run: mvn clean
      - run: mvn package
