name: Automatic push on commit
run-name: "petclinic deployment"
on: [push]
env:
  DATETIME: date +%m%d%H%M%Y
jobs:
  Deploy-Petclinic:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /home/runner/work/petclinic/petclinic
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - run: |
          mvn clean
          mvn package
          git config --global user.name 'rick-limmen'
          git config --global user.email 'rick.limmen@devoteam.com'
          git add -A; git commit -m 'automatic build push'
          git push
