name: Automatic push on commit
run-name: "petclinic deployment"
on: [push]
env:
  DATETIME: date +%m%d%H%M%Y
jobs:
  Build-Petclinic:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /home/runner/work/petclinic/petclinic
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - run: |
          mvn clean
          mvn package
      - name: Upload .war file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: make war available for download
          path: /home/runner/work/petclinic/petclinic/target/*.war
